import { z } from 'zod';

export const WebGLSectionConfigSchema = z.object({
    // The 'sceneMode' tells WebGLManager which module to load (e.g. 'logo-centerpiece')
    sceneMode: z.string().optional(),

    // High-priority 3D asset generated by the Blender MCP Pipeline
    centerpieceSource: z.string().optional(),

    // Custom aesthetics applied to this specific section's 3D rendering
    materialOverride: z.string().optional(),
    ambientIntensity: z.number().default(1.0),
});

export const NormalizedSectionSchema = z.object({
    id: z.string(),
    type: z.enum(['hero', 'gallery', 'text', 'custom']),

    // Contains text, images, videos
    media: z.object({
        images: z.array(z.string()).default([]),
        videos: z.array(z.string()).default([]),
    }),

    // Link to the WebGL rendering logic!
    webgl: WebGLSectionConfigSchema.optional(),
});

export type NormalizedSection = z.infer<typeof NormalizedSectionSchema>;
